version: '3.1'

services:

  frontend:
    image: stealthybox/vr-swarm
    volumes:
    # mount source code for development
    - ./build:/app/build
    - ./config:/app/config
    - ./src:/app/src
    - ./static:/app/static
    - ./index.html:/app/index.html
    deploy:
      labels:
        traefik.port: 8080
        traefik.docker.network: lb_proxy
        traefik.frontend.rule: PathPrefix:/
    networks:
    - lb_proxy

  docker-api:
    image: ehazlett/docker-proxy:latest
    command: -i
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
        - node.role == manager
      labels:
        traefik.port: 2375
        traefik.docker.network: lb_proxy
        traefik.frontend.rule: PathPrefixStrip:/docker
    networks:
    - lb_proxy

networks:
  lb_proxy:
    external: true
